---
- name: Cleanup steps
  block:
  # - name: Destroy VMs
  #   virt:
  #     command: destroy
  #     name: "{{ vm_name_prefix ~'-%s' | format(item) }}"
  #   register: result
  #   failed_when: >
  #     '"domain is not running" not in result.stderr'
  #   loop: "{{ range(0, guest_vms_count) | list }}"
  - name: List VMs
    virt:
      command: list_vms
    register: all_vms

  - name: Undefine VMs
    virt:
      command: undefine
      name: "{{ item }}" 
    loop: "{{ all_vms['list_vms'] }}"

  - name: Cleanup the disk images
    file:
        path: "{{ vms_image_location }}/{{ item }}.qcow2'}}" 
        state: absent 
    loop: "{{ all_vms['list_vms'] }}"
  - name: Remove VMs from BMC service
    shell: >-
      vbmc delete {{item}}
    loop: "{{ all_vms['list_vms'] }}"
  when: clean_vms|bool
  tags: clean_only